GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: 1

###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title":"Chest and Leg Workout",
    "content":"Easy Warm up workout",
    "category":"Weight Training ",
    "duration":"45 min",
    "exercises":[{"name":"Bench Press","sets":"3", "reps":"10","weight":"135"}, {"name":"Squat","sets":"2", "reps":"15","weight":"100"} ]
    
}

###


DELETE http://localhost:3000/api/posts
Content-Type: application/json

{
    "id":"636a9130f4c964f6781a7daa"
}