POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title":"Chest Workout",
    "content":"Focused on dumbbells this session",
    "category":"Weight Training ",
    "duration":"45 min",
    "exercises":"treadmill"
    
}

###


DELETE http://localhost:3000/api/posts
Content-Type: application/json

{
    "id":"636a9130f4c964f6781a7daa"
}