GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hbGFtYWxhIiwidXNlcklkIjoiNjM2ZWIyYTU0OGJlNWI3Y2YzMWViNDJkIiwiaWF0IjoxNjY4NDg4MjE2LCJleHAiOjE2Njg1NzQ2MTZ9.ZYEqBJM6bFWTy03hDJGvq_35uacsetHjHHcQWIgQ7bI

###

GET http://localhost:3000/api/posts
Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hbGFtYWxhIiwidXNlcklkIjoiNjM2ZWIyYTU0OGJlNWI3Y2YzMWViNDJkIiwiaWF0IjoxNjY4NDg4MjE2LCJleHAiOjE2Njg1NzQ2MTZ9.ZYEqBJM6bFWTy03hDJGvq_35uacsetHjHHcQWIgQ7bI


###


DELETE http://localhost:3000/api/posts
Content-Type: application/json

{
    "id":"636a9130f4c964f6781a7daa"
}